{{< pagebreak >}}

# Introduction

The rising prevalence of type 2 diabetes constitutes an escalating global health burden[@saeedi2019]. Identifying and characterising individuals at high risk of type 2 diabetes is essential to public health prevention efforts. [JS: I dont see IFG and IGT are used to risk stratify, but used to classify prediabetes] Impaired fasting glucose (IFG) and impaired glucose tolerance (IGT) currently define high-risk individuals, each regarded to have different pathophysiology of insulin resistance and beta-cell dysfunction[@defronzo2004]. Although glucose patterns during an oral glucose tolerance test (OGTT) help characterise types of prediabetes, they provide limited insight into broader metabolic heterogeneity [JS: I am unsure what the message is in this sentence. I think it need some more context. Is it becuase it is only based on glycemic fasting + response? and high risk individual can be defined by more that glycemia risk factors?]. While heterogeneity in type 2 diabetes is well-established [@ahlqvist2018; @tobias2023], emerging evidence suggests that metabolic heterogeneity is already present before diabetes onset, highlighting an opportunity for risk stratification and more targeted prevention strategies [@wagner2021; @stroebel2025]. [JS: Overall comment: In the beginning, I read it as being focused on glycemia, which I think makes sense, but I need something to make sure that when you refer to metabolic heterogeneity, it is about including more dimensions of metabolic health (e.g., lipids, liver health, inflammation etc.). This can bridge to the next part, which focuses on including other dimensions in response to the OGTT.]

Beyond glucose, the OGTT captures postload hormonal responses that may represent another dimension of metabolic heterogeneity. The incretin effect, which is the elevates insulin response to oral versus intravenous glucose[]. This response is primarily driven by glucagon-like peptide-1 (GLP-1) and glucose-dependent insulinotropic polypeptide (GIP), that supports stimulation [JS: when using the word "important". Make sure to describe the function, to be specific] postprandial insulin response and regulates glucose [@holst2019]. GLP-1 enhances insulin secretion[JS: You have mentioned insulin secretion in the previous sentence. If you want to be more specific, I suggest doing it there, and then moving forward to the incretin effect on glucagon.] and suppresses glucagon, while GIP primarily stimulates insulin secretion. This makes GLP-1 a key regulator of postprandial glucose, further supported by the success of GLP-1-based therapies in treating type 2 diabetes and obesity [@holst2024]. In contrast to the glucose-lowering mechanisms of GLP-1 and GIP, glucagon increases glucose levels by stimulating glycogenolysis in the liver, making its suppression during glucose intake essential for normal glucose regulation [@ahrén2015]. However, the interplay between incretin secretion and glucagon suppression among individuals with impaired glucose metabolism is complex, underscored by conflicting findings in the literature. Incretin secretion has been found to be decreased [@toft-nielsen2001], normal [@vollmer2008] and increased [@færch2008] among individuals with impaired glucose metabolism. Similarly, glucagon suppression appears to vary with insulin sensitivity, as individuals with prediabetes or screen-detected type 2 diabetes exhibit impaired early but relatively normal late glucagon suppression, whereas individuals with higher insulin sensitivity show higher early but lower late glucagon suppression [@færch2016; @wagner2017].

[JS: **READ FIRST** Overall comment about this section
This almost reads as a review about incretins and glucagon. I think it would benifit to be made closer to you story. An idea could be:
- Responses other than glucose to the OGTT provide further information about the heterogeneity.
- Recently, incretins and glucagon have gained much attention as therapeutic targets to improve metabolic health.
- The incretins secreted from the intestines support stimulation of insulin secretion and glucose uptake, while glucagon stimulates glucose production during fasting.
- Present the gap: e.g. earlier studies have investigated differences in natural incretin and glucagon responses between glycemic groups, but none have investigated whether incorporating incretin and glucagon responses into subgrouping of glucose and insulin dynamics identifies distinct metabolic subgroups].

[JS: ]
Additionally, body fat distribution represents another important dimension of metabolic heterogeneity and, in particular, visceral adipose tissue (VAT) and subcutaneous adipose tissue (SAT) are closely linked to both insulin resistance and beta-cell function [@kahn2001a]. Moreover, differences in fat distribution are already observed across normal glucose tolerance, prediabetes and newly diagnosed type 2 diabetes [@borel2015]. This is further supported by recent phenotyping studies identifying subgroups with distinct characteristics, including diverse patterns of body fat distribution [@wagner2021; @stroebel2025]. However, while both hormonal responses and body fat distribution are recognised as important contributors to metabolic risk, these dimensions are typically studied separately. Furthermore, the clinical use of incretin-based therapies in treating both glycemia and obesity highlights the relevance of incretins, and raises the question of whether endogenous incretin and glucagon secretion relate to body fat distribution. In this context, the interplay between glucose, insulin, incretin and glucagon responses during an OGTT, and how these response patterns relate to measures of body fat distribution remains unclear. The aim of this study was to identify metabolic subgroups among individuals across the glycemic spectrum, from normoglycemia to screen-detected type 2 diabetes, using K-means clustering of OGTT-derived glucose and hormonal responses and to quantify the associations between these subgroups and measures of body fat distribution.
