# 

{{< pagebreak >}}

# Declarations

**Funding**\
The ADDITION-PRO study received funding from the European Foundation for the Study of Diabetes/Pfizer for Research into Cardiovascular Disease Risk Reduction in Patients with Diabetes (74550801). Additionally, the study was supported by internal research and equipment funds from Steno Diabetes Center A/S. The funders had no influence on the study design, data collection and analysis, decision to publish, or preparation of the manuscript.

**Competing interests**\
The authors have no relevant financial or non-financial interests to disclose.

**Ethics approval**\
The ADDITION-PRO study was approved by the Scientific Ethics Committee of the Central Denmark Region (reference no. 20080229) and conducted in accordance with the principles of the Declaration of Helsinki.

**Consent to participate**\
All participants provided both oral and written informed consent.

**Consent for publication**\
Not applicable.

**Availability of data and material**\
The data used in this study are not publicly available. Access to ADDITION-PRO data may be granted upon request and approval by the ADDITION-PRO Steering Committee.

The project, including the manuscript and code for the analyses and figures, is available at: <https://github.com/MSteentoft/ogtt-heterogeneity-study>
