```{=latex}
\setstretch{1.5}
```

# Thesis structure {.unnumbered .unlisted}

This thesis assesses heterogeneity among individuals at high risk of type 2 diabetes by identifying metabolic subgroups with different postload glucose and hormonal response patterns, and by quantifying the associations between these subgroups and measures of body fat distribution.

The thesis is structured in two main sections: A paper manuscript and an appendix comprised of sections A, B and C.

The paper manuscript with the title: *Heterogeneity in GLP-1, GIP and glucagon responses during an oral glucose tolerance test among individuals at high risk of type 2 diabetes* is structured according to the instructions for authors for the journal *Diabetes Care* and includes Abstract, Introduction, Research Design and Methods, Conclusions, References, table and figure legends and Supplementary material.

In appendix A, the epidemiological considerations about the study design and population will be elaborated, analyzed and discussed, while appendix B contains a more detailed description and discussion of the statistical clustering approach. Finally, the literature search on which the thesis was based on is presented in appendix C.
